
create table if not exists role
(
    id  integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name VARCHAR(10)
);
INSERT INTO role (name)
VALUES
    ('USER'),
    ('ADMIN');
create table if not exists image
(
    id  integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_default blob
);
INSERT INTO image (user_default)
VALUES
    (null),
    (null);

-- create table if not exists post
-- (
--     id  integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
--     created_at date,
--     content VARCHAR(255),
--     author_id int
-- );
-- INSERT INTO role (name)
-- VALUES
--     ('USER'),
--     ('ACTIVE');

create table if not exists user
(
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    first_name VARCHAR(255),
    last_name  VARCHAR(255) ,
    email      VARCHAR(255),
    password   VARCHAR(255),
    user_picture blob,
    status     VARCHAR(255)
);
INSERT INTO user (first_name,last_name,email,password,user_picture, status)
VALUES
    ('Danie','Yockney','dyockney1@biblegateway.com','123', null, 'ACTIVE'),
    ('Joe','STa','joe@email.com','123', null, 'ACTIVE');



